### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by CertifiedClown** [01-Feli/ServerStatusBot#14]
hey mate i dont understand the docker part could you help me or be more specific?

**Comment by 1310s** [comment]
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/Users/hvnull/Desktop/server/ServerStatusBot/ServerStatusBot/appsettings.Production.json" to rootfs at "/app/appsettings.json": mount /run/desktop/mnt/host/c/Users/hvnull/Desktop/server/ServerStatusBot/ServerStatusBot/appsettings.Production.json:/app/appsettings.json (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by negrifelipe** [comment]
Hi, inside the bot folder have you created the appsettings.Production.json?

**Comment by negrifelipe** [comment]
Closing as there is no response

**Comment by CertifiedClown** [comment]
sorry for not answering. is much to ask if you could make a quick video of the steps i keep getting errors.

**Comment by negrifelipe** [comment]
Hi, as it's pretty simple to set up I am not not planning on making a YouTube video. Please if you need help answer the question I asked you.
