### ISSUE TITLE
NaN Playtime

### ISSUE THREAD

**Issue by papershredder432** [01-Feli/ServerStatusBot#4]
Playtime shows as NaN for days/hours/minutes/seconds

![image](https://user-images.githubusercontent.com/34615274/114296721-cf53df00-9a7a-11eb-855b-7883fb6c05c8.png)

**Comment by shsadi95** [comment]
some

**Comment by papershredder432** [comment]
> some

Do you mean "same"?

**Comment by 01-Feli** [comment]
I will take a look at the code and see why that is happening

**Comment by 01-Feli** [comment]
@papershredder432 you can find the update on the source code or releases

**Comment by papershredder432** [comment]
Yes that had fixed it @01-Feli 
![image](https://user-images.githubusercontent.com/34615274/114544378-8772ba80-9c28-11eb-9852-4e0bd25214de.png)


Sorry for the late reply!
